app:
  port: 3400
  secret: 'secret'
  frontendUrl: 'http://localhost:3000'

# Only for technical assessment purposes, in a real world scenario, this should be stored in a secure way
db:
  uri: 'postgres://kata_user:kata_pass@localhost:5432/kata_db'
  host: localhost
  port: 5432
  database: kata_db
  user: kata_user
  password: kata_pass

auth0:
    domain: dev-wtwyfkpnfrmqfjgv.us.auth0.com
    audience: https://dev-wtwyfkpnfrmqfjgv.us.auth0.com/api/v2/
    clientId: gV95MEgDa0yWgrZTsB9mZ7GLSksyLTKy
    clientSecret: luyx7dQCzo8CXYs4Agyyfn5FCbvff_BBJ3Xm-ygbnZEkRA0aj3UHG2bvlA12azyN

nodemailer:
    service: 'gmail'
    host: 'smtp.gmail.com'
    port: 587
    secure: false
    auth:
        user: 'kataassessment@gmail.com'
        pass: 'upzalfnwsnnzgpja'
    #pass: '@KataTest2025'
